export const TABLE_HEADER_USER = ['NO', 'NAME', 'ROLE', 'ACTIONS'];
export const TABLE_HEADER_MENU = ['NO', 'NAME', 'CATEGORY', 'PRICE', 'DISCOUNT', 'AVAILABLE', 'ACTIONS'];
export const TABLE_HEADER_TABLE = ['NO', 'NAME', 'DESCRIPTION', 'CAPACITY', 'STATUS', 'ACTIONS'];
export const TABLE_HEADER_ORDER = ['NO', 'ORDER ID','CUSTOMER NAME', 'TABLE NAME','STATUS','ACTIONS'];


