import { DarkModeToggle } from "@/components/common/darkmode-toggle"
import { Metadata } from "next";
import { ReactNode } from "react"

type AuthLayoutProps={
    children:ReactNode
}

export const metadata: Metadata = {
    title: "RESTOKU | Payment Status",
    description: "Generated by create next app",
    icons: {
        icon: "/icon.png",
    },
};

export default function PaymentLayout({children}:AuthLayoutProps) {
    return (
        <div className="relative bg-background flex min-h-svh items-center justify-center">
            <div className="absolute top-4 right-4">
                <DarkModeToggle/>
            </div>
            <div  className="flex w-full flex-col">
                {children}
            </div>
        </div>
    )
}